config/routes.rb
DailyQueue::Application.routes.draw do
  
  
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [ :sessions ] do
    get "/login" => "sessions#new", :as => "new_user_session"
    post "/login" => "sessions#create", :as => "user_session"
    delete "/logout" => "sessions#destroy", :as => "destroy_user_session"
    get "/register" => "devise/registrations#new", :as => "new_user_registration"
  end
  
  match "profile" => "queue#show", :as => "profile"
  match "add" => "queue#add", :as => "add", :via => [:post]
  match "delete" => "queue#delete", :as => "delete", :via => [:delete]
  
  scope :module => "admin" do
    resources :links, :link_collections
    resources :users, :except => [:new ]
  end
  
  
  
  
  
  
  
  
  
  
  root :to => "queue#index"
  
  
end

app/models/link_collection.rb
class LinkCollection < ActiveRecord::Base
  belongs_to :user
  has_many :links
  after_destroy :destroy_orphaned_links
  
  private
  
  def destroy_orphaned_links
    links.each do |link|
      link.destroy if !link.link_collection
    end
  end
end

app/controllers/admin/link_collections_controller.rb
class Admin::LinkCollectionsController < ApplicationController
  before_filter :authenticate_admin!
  # GET /link_collections
  # GET /link_collections.xml
  def index
    @link_collections = LinkCollection.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @link_collections }
    end
  end

  # GET /link_collections/1
  # GET /link_collections/1.xml
  def show
    @link_collection = LinkCollection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link_collection }
    end
  end

  # GET /link_collections/new
  # GET /link_collections/new.xml
  def new
    @link_collection = LinkCollection.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link_collection }
    end
  end

  # GET /link_collections/1/edit
  def edit
    @link_collection = LinkCollection.find(params[:id])
  end

  # POST /link_collections
  # POST /link_collections.xml
  def create
    @link_collection = LinkCollection.new(params[:link_collection])

    respond_to do |format|
      if @link_collection.save
        format.html { redirect_to(@link_collection, :notice => 'Link collection was successfully created.') }
        format.xml  { render :xml => @link_collection, :status => :created, :location => @link_collection }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link_collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /link_collections/1
  # PUT /link_collections/1.xml
  def update
    @link_collection = LinkCollection.find(params[:id])

    respond_to do |format|
      if @link_collection.update_attributes(params[:link_collection])
        format.html { redirect_to(@link_collection, :notice => 'Link collection was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link_collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /link_collections/1
  # DELETE /link_collections/1.xml
  def destroy
    @link_collection = LinkCollection.find(params[:id])
    @link_collection.destroy

    respond_to do |format|
      format.html { redirect_to(link_collections_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/link_collections_helper.rb
module LinkCollectionsHelper
end

app/views/admin/link_collections/_form.html.erb
<%= form_for(@link_collection) do |f| %>
  <% if @link_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link_collection.errors.count, "error") %> prohibited this link_collection from being saved:</h2>

      <ul>
      <% @link_collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/link_collections/edit.html.erb
<h1>Editing link_collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_collection %> |
<%= link_to 'Back', link_collections_path %>

app/views/admin/link_collections/index.html.erb
<h1>Listing link_collections</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @link_collections.each do |link_collection| %>
  <tr>
    <td><%= link_collection.user_id %></td>
    <td><%= link_to 'Show', link_collection %></td>
    <td><%= link_to 'Edit', edit_link_collection_path(link_collection) %></td>
    <td><%= link_to 'Destroy', link_collection, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link collection', new_link_collection_path %>

app/views/admin/link_collections/new.html.erb
<h1>New link_collection</h1>

<%= render 'form' %>

<%= link_to 'Back', link_collections_path %>

app/views/admin/link_collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @link_collection.user_id %>
</p>


<%= link_to 'Edit', edit_link_collection_path(@link_collection) %> |
<%= link_to 'Back', link_collections_path %>