config/routes.rb
DailyQueue::Application.routes.draw do
  
  
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [ :sessions ] do
    get "/login" => "sessions#new", :as => "new_user_session"
    post "/login" => "sessions#create", :as => "user_session"
    delete "/logout" => "sessions#destroy", :as => "destroy_user_session"
    get "/register" => "devise/registrations#new", :as => "new_user_registration"
  end
  
  match "profile" => "queue#show", :as => "profile"
  match "add" => "queue#add", :as => "add", :via => [:post]
  match "delete" => "queue#delete", :as => "delete", :via => [:delete]
  
  scope :module => "admin" do
    resources :links, :link_collections
    resources :users, :except => [:new ]
  end
  
  
  
  
  
  
  
  
  
  
  root :to => "queue#index"
  
  
end

app/controllers/queue_controller.rb
class QueueController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :except => [ :index ]
  
  def index
    if user_signed_in?
      redirect_to profile_path
    end
  end
  
  def show
    
  end
  
  def add
    if params[:url] == ""
      redirect_to profile_path, :alert => "urls cannot be blank"
    else
      @link_collection = nil
      @link = Link.new(:url => params[:url])
      if current_user
        if current_user.link_collections.length != 0
          @link_collection = current_user.link_collections.first
        else
          @link_collection = LinkCollection.new(:user_id => current_user.id)
          @link_collection.save
        end
      end
      
      respond_to do |format|
        if @link_collection
          @link.link_collection_id = @link_collection.id
          @link.save
          flash[:notice] = "link successfully added to queue"
          format.html { redirect_to profile_path }
          format.xml  { render :xml => @link, :status => :created, :location => @link }
          format.json { render :json => @link, :status => :created, :location => @link }
          format.js { @current_item = @link }
        else
          format.html { redirect_to user_queue_path(params[:user]), :alert => "failed to add link" }
          format.xml  { render :json => @link.errors, :status => "failed" }
          format.json { render :json => @link.errors, :status => "failed" }
          format.js
        end
      end
    end
  end
  
  def delete
    @link = Link.find(params[:id])
    @link_collection = LinkCollection.find_by_id(@link.link_collection_id)
    @link.destroy
    
    respond_to do |format|
      flash[:notice] = "deleted link successfully"
      format.html { redirect_to(profile_path) }
      format.js
      format.xml  { head :ok }
    end
  end
end

app/helpers/queue_helper.rb
module QueueHelper
end

app/views/queue/index.html.erb
<p id="about-blurb">
	Are you ever at work, in the zone, getting spammed by links from co-workers/friends? Wouldn't it be nice to store those links away for later viewing?
	That is what your <b>DailyQueue</b> is for. <b>DailyQueue</b> is a web service that will store/organize and navigate to your saved links. It is accompanied
	by a desktop app that allows you to quickly send a link in your clipboard to your <b>DailyQueue</b> account. This lets you add a link seamlessly, without being interrupted.
</p>

app/views/queue/show.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Untitled Document</title>
	</head>
	<body>
		<h1>This is the queue for <%= current_user.username %>!</h1>
	</body>
	<%= form_tag(add_path, :method => "post") do %>
	<input type="text" name="url"/>
	<input type="submit" value="Add"/>
<% end %>
			<% current_user.link_collections.each do |link_collection| %>
	<div id="user-queue">

<table>
    <% link_collection.links.each do |link| %>
    <tr>
        <td>
        	<%= button_to 'delete', delete_path(:id => link.id), :confirm => 'Are you sure?', :method => :delete %>
            <a href='<%= link.url %>'><%= link.url %></a>
			
        </td>
    </tr>
    <% end %>
</table>
</div>
<% end %>
</html>

app/views/queue/show.json.erb
{success => true, authenticity_token => '<%=form_authenticity_token%>'}