config/routes.rb
DailyQueue::Application.routes.draw do
  
  
  devise_for :users, :controllers => {:sessions => 'sessions'}, :skip => [ :sessions ] do
    get "/login" => "sessions#new", :as => "new_user_session"
    post "/login" => "sessions#create", :as => "user_session"
    delete "/logout" => "sessions#destroy", :as => "destroy_user_session"
    get "/register" => "devise/registrations#new", :as => "new_user_registration"
  end
  
  match "profile" => "queue#show", :as => "profile"
  match "add" => "queue#add", :as => "add", :via => [:post]
  match "delete" => "queue#delete", :as => "delete", :via => [:delete]
  
  scope :module => "admin" do
    resources :links, :link_collections
    resources :users, :except => [:new ]
  end
  
  
  
  
  
  
  
  
  
  
  root :to => "queue#index"
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :link_collections
  after_destroy :destroy_orphaned_link_collections
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  
  private
  
  def destroy_orphaned_link_collections
    link_collections.each do |link_collection|
      link_collection.destroy if !link_collection.user
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_admin!
  
  def index
    @users = User.where("admin = ?", false)
  end
  
  #def new
  #  @user = User.new
  #end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to users_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to users_path
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>prohibited this user from being saved:</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<p>
    <%= f.label :username %>
    <br/>
    <%= f.text_field :username %>
</p>
<p>
    <%= f.label :email %>
    <br/>
    <%= f.text_field :email %>
</p>
<p>
    <%= f.label :password %>
    <br/>
    <%= f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation %>
    <br/>
    <%= f.password_field :password_confirmation %>
</p>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
	<td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>